name:                threaded
version:             0.0.0
github:              "athanclark/threaded"
license:             BSD3
author:              "Athan Clark"
maintainer:          "athan.clark@gmail.com"
copyright:           "2020 Athan Clark"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Manage concurrently operating threads without having to spark them
category:            Concurrent

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/athanclark/threaded#readme>

dependencies:
- base >= 4.7 && < 5
- async
- chan
- extractable-singleton
- hashable
- monad-control-aligned
- mtl
- stm
- tmapmvar

library:
  source-dirs: src

tests:
  threaded-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - threaded
